### ISSUE TITLE
PassSlot Gem not in RubyGems

### ISSUE THREAD

**Issue by shenoudab** [passslot/passslot-ruby-sdk#1]
Dears, 

 i was trying to install PASSSlot Gem for trying it .. but i didn't find it and got the following:

ERROR:  Could not find a valid gem 'passslot' (>= 0) in any repository

Also, i download the code and use my APIKey and Template Name but i also got the error "API Error: Something went wrong"

Also, how can i generate template from this SDK .. also push the generated pass to a specific user with their mobile number.

any help.

**Comment by passslot** [comment]
Hi

The gem is not yet available on rubygems but we will publish it as soon as possible. In the meantime you can use the gem by referencing our repository like this in your Gemfile

`gem 'passslot', :git => 'git://github.com/passslot/passslot-ruby-sdk.git'`

You can send us your details about the errors you are getting to support@passslot.com

Kind regards
